Fix test search for mulled container hashes
Fixes
```
FAILED test/unit/tool_util/mulled/test_get_tests.py::test_hashed_test_search - AssertionError: assert ['bamtools --help'] == ['bamtools --help', 'samtools --help']
  Right contains one more item: 'samtools --help'
  Full diff:
  - ['bamtools --help', 'samtools --help']
  + ['bamtools --help']
```
(again). The test broke with the addition of
`osx-64/samtools-1.3.1-h0840685_11.tar.bz2` 4 days ago.