Fix parsing of `scontrol show job`
Fix the following traceback:
```
galaxy.jobs.runners.slurm ERROR 2018-05-22 13:01:07,050 (1024816/14094939) Failure in SLURM _complete_terminal_job(), job final state will be: failed
Traceback (most recent call last):
  File "/tgac/services/galaxy/prod/galaxy/lib/galaxy/jobs/runners/slurm.py", line 86, in _complete_terminal_job
    slurm_state = _get_slurm_state()
  File "/tgac/services/galaxy/prod/galaxy/lib/galaxy/jobs/runners/slurm.py", line 81, in _get_slurm_state
    job_info_dict = dict([out_param.split('=', 1) for out_param in stdout.split()])
ValueError: dictionary update sequence element #52 has length 1; 2 is required
```