Import ``ImporterGalaxyInterface`` from its module
Fix the following issue in package tests with gxformat2 0.26.0:

```
Traceback:
/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
galaxy/app.py:74: in <module>
    from galaxy.managers.workflows import (
galaxy/managers/workflows.py:17: in <module>
    from gxformat2 import (
E   ImportError: cannot import name 'ImporterGalaxyInterface' from 'gxformat2'
```

(cherry picked from commit 981cadc8f1bdcda8a899d5b231f26278ac99f53d)