Fix linting error on python 3 if no version is defined
Fixes
```
Traceback (most recent call last):
  File "/Users/mvandenb/.pyenv/versions/3.6.9/bin/planemo", line 11, in <module>
    load_entry_point('planemo', 'console_scripts', 'planemo')()
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/mvandenb/src/planemo/planemo/cli.py", line 190, in handle_blended_options
    return f(*args, **kwds)
  File "/Users/mvandenb/src/planemo/planemo/commands/cmd_lint.py", line 58, in cli
    recursive=kwds["recursive"]
  File "/Users/mvandenb/src/planemo/planemo/tool_lint.py", line 33, in lint_tools_on_path
    if not lint_tool_source(tool_xml, name=basename(tool_path), **lint_args):
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/galaxy/tool_util/lint.py", line 18, in lint_tool_source
    lint_tool_source_with(lint_context, tool_source, extra_modules)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/galaxy/tool_util/lint.py", line 54, in lint_tool_source_with
    lint_context.lint(name, value, tool_source)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/galaxy/tool_util/lint.py", line 83, in lint
    lint_func(lint_target, self)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/galaxy/tool_util/linters/general.py", line 27, in lint_general
    parsed_version = packaging.version.parse(version)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/packaging/version.py", line 28, in parse
    return Version(version)
  File "/Users/mvandenb/.pyenv/versions/3.6.9/lib/python3.6/site-packages/packaging/version.py", line 219, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```