Restore all environment variables at the end of Keycloak integration tests
not just `OAUTHLIB_INSECURE_TRANSPORT`.

Fix the following error in integration tests that were run after
those in `test/integration/oidc/test_auth_oidc.py`:

```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1147)
```

Introduced in https://github.com/galaxyproject/galaxy/pull/16977 .