Type annotation fix for mypy 1.16.0 during package testing
Fix the following traceback:

```
galaxy/selenium/context.py:25: error: Cannot override writeable attribute with
read-only property  [override]
        def driver(self):
        ^
```

This error didn't happen during the normal `tox -e mypy` because
the `selenium` package was not installed into the tox virtual environment.

To prevent this issue and improve the code type checking, this commit
defines a new `test` dependency group and corresponding
`lib/galaxy/dependencies/pinned-test-requirements.txt` requirements
file to be used by mypy and other tests that don't need packages
used purely for developing (like black, isort, Sphinx...).

Fix the 6 new mypy errors resulting from installing the test
dependencies into the tox virtual environment.