Do not pollute param_dict with a non JSONifiable dict
When running a data manager with a dataset parameter, the job fails
with the following backtrace:

Traceback (most recent call last):
  File "/opt/galaxy/lib/galaxy/jobs/runners/__init__.py", line 166, in prepare_job
    job_wrapper.prepare()
  File "/opt/galaxy/lib/galaxy/jobs/__init__.py", line 885, in prepare
    tool_evaluator.set_compute_environment( compute_environment, get_special=get_special )
  File "/opt/galaxy/lib/galaxy/tools/evaluation.py", line 107, in set_compute_environment
    self.tool.exec_before_job( self.app, inp_data, out_data, param_dict )
  File "/opt/galaxy/lib/galaxy/tools/__init__.py", line 1956, in exec_before_job
    out.write( json.dumps( (json_params) ).encode('utf8') )
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string

The bug was introduced in PR #2029.