Better error message for unknown `ShellJobRunner` shell plugin
Instead of raising:

```
  File "/srv/galaxy/lib/galaxy/jobs/runners/util/cli/__init__.py", line 78, in get_shell_plugin
    self.active_cli_shells[requested_shell_settings] = self.cli_shells[shell_plugin](**shell_params)
KeyError: 'ZecureShell'
```

raise:

```
  File "/srv/galaxy/lib/galaxy/jobs/runners/util/cli/__init__.py", line 80, in get_shell_plugin
    raise ValueError(f"Unknown shell_plugin [{shell_plugin}], available plugins are {list(self.cli_shells.keys())}")
ValueError: Unknown shell_plugin [ZecureShell], available plugins are ['RemoteShell', 'SecureShell', 'GlobusSecureShell', 'ParamikoShell', 'LocalShell']
```