Note `cannot import name _remove_dead_weakref` error and solution
Having a different Python version on the Galaxy server vs the compute nodes can cause an error including the message `ImportError: cannot import name _remove_dead_weakref`. This adds text to describe the error and its resolution