Replace argument with [] only if None
For example a `ToolRequirements` argument of length 0 evaluates to
False and was replaced, causing the following obscure integration
test failures:

```
INFO     pulsar.managers.stateful:stateful.py:64 Status of job [4] changed to [failed]. No callbacks enabled.
ERROR    pulsar.managers.stateful:stateful.py:143 Failed job preprocessing for job 4:
Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/pulsar/managers/stateful.py", line 132, in _handling_of_preprocessing_state
    **launch_kwds
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/pulsar/managers/queued.py", line 54, in launch
    setup_params=setup_params
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/pulsar/managers/unqueued.py", line 54, in _prepare_run
    setup_params=setup_params
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/pulsar/managers/base/directory.py", line 120, in _setup_job_file
    command_line = self._expand_command_line(command_line, dependencies_description, job_directory=self.job_directory(job_id).job_directory)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/pulsar/managers/base/__init__.py", line 197, in _expand_command_line
    job_directory=job_directory,
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/tool_util/deps/__init__.py", line 185, in dependency_shell_commands
    requirements_to_dependencies = self.requirements_to_dependencies(requirements, **kwds)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/tool_util/deps/__init__.py", line 195, in requirements_to_dependencies
    requirement_to_dependency = self._requirements_to_dependencies_dict(requirements, **kwds)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/tool_util/deps/__init__.py", line 213, in _requirements_to_dependencies_dict
    resolvable_requirements = requirements.resolvable
AttributeError: 'list' object has no attribute 'resolvable'
```

Also rename variable name from `dict` to `d` to not use standard library reserved words.