Fix mypy error due to packaging 26.0
Fix:

```
lib/galaxy/tool_util/version.py:60: error: Property "_key" defined in "_BaseVersion" is read-only  [misc]
            self._key = _legacy_cmpkey(self._version)
            ^~~~~~~~~
```

(cherry picked from commit c302820b4f46823acf9d459d57c6393d5f2c405e)