Raise detailed exception for broken citation
For an empty citation, this will result in logging:
```
Exception: Invalid citation of type 'doi' with content 'None': 'NoneType' object has no attribute 'strip'
```

instead of:
```
AttributeError: 'NoneType' object has no attribute 'strip'
```

xref https://github.com/galaxyproject/planemo/issues/929