Fix lint warning string formatting
Introduced in
https://github.com/mvdbeek/galaxy/commit/c4fabf05e11c033006834fd0bf0d9077c0156134,
causes:
```
ValueError: unsupported format character 'n' (0x6e) at index 16
```