Don't serialize ratings, reviews and reviewers
These would need need custom to_dict functions, else they fail with
```
TypeError: Object of type RepositoryRatingAssociation is not JSON serializable
  File "galaxy/web/framework/decorators.py", line 171, in decorator
    rval = format_return_as_json(rval, jsonp_callback, pretty=trans.debug)
  File "galaxy/web/framework/decorators.py", line 329, in format_return_as_json
    json = safe_dumps(rval, **dumps_kwargs)
  File "galaxy/util/json.py", line 67, in safe_dumps
    dumped = json.dumps(*args, allow_nan=False, **kwargs)
  File "json/__init__.py", line 234, in dumps
    return cls(
  File "json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
```
I think this has never worked since its addition in
https://github.com/galaxyproject/galaxy/pull/8661.