bump mercurial
```
galaxy.tool_shed.util.hg_util ERROR 2025-02-25 14:01:10,758 [pN:main.4,p:21583,tN:WSGI_4] Error cloning repository: Command '['hg', 'clone', '--stream', '-r', '3', 'https://toolshed.g2.bx.psu.edu/repos/ufz/omero_filter', '/gpfs1/data/galaxy_server/galaxy/shed_tools/toolshed.g2
.bx.psu.edu/repos/ufz/omero_filter/f79a1bf2f386/omero_filter']' returned non-zero exit status 1.
Output was:
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/.venv/bin/hg", line 57, in <module>
    from mercurial import dispatch
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.12/site-packages/hgdemandimport/demandimportpy3.py", line 52, in exec_module
    super().exec_module(module)
  File "<frozen importlib.util>", line 257, in exec_module
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.12/site-packages/hgdemandimport/demandimportpy3.py", line 52, in exec_module
    super().exec_module(module)
  File "<frozen importlib.util>", line 267, in exec_module
AttributeError: partially initialized module 'threading' has no attribute 'RLock' (most likely due to a circular import)

galaxy.tool_shed.galaxy_install.install_manager ERROR 2025-02-25 14:01:10,758 [pN:main.4,p:21583,tN:WSGI_4] Error installing repository 'omero_filter'
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tool_shed/galaxy_install/install_manager.py", line 521, in install_repositories
    self.install_tool_shed_repository(
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tool_shed/galaxy_install/install_manager.py", line 619, in install_tool_shed_repository
    raise Exception(error_message)
Exception: Error cloning repository: Command '['hg', 'clone', '--stream', '-r', '3', 'https://toolshed.g2.bx.psu.edu/repos/ufz/omero_filter', '/gpfs1/data/galaxy_server/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/ufz/omero_filter/f79a1bf2f386/omero_filter']' returned non-ze
ro exit status 1.
Output was:
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/.venv/bin/hg", line 57, in <module>
    from mercurial import dispatch
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.12/site-packages/hgdemandimport/demandimportpy3.py", line 52, in exec_module
    super().exec_module(module)
  File "<frozen importlib.util>", line 257, in exec_module
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.12/site-packages/hgdemandimport/demandimportpy3.py", line 52, in exec_module
    super().exec_module(module)
  File "<frozen importlib.util>", line 267, in exec_module
AttributeError: partially initialized module 'threading' has no attribute 'RLock' (most likely due to a circular import)
```

an update seemed to work also in other places https://github.com/msys2/MSYS2-packages/issues/4836