Pin ubuntu 22.04 for minikube setup action
The `ubuntu-latest` runner label is moving to 24.04, see https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/

Fixes https://github.com/galaxyproject/galaxy/actions/runs/11260477825/job/31317049837?pr=18963:
```
No VM guests are running outdated hypervisor (qemu) binaries on this host.
/usr/bin/lsb_release --short --codename
noble
Error: Unexpected HTTP response: 404
```