Fix unit tests returning values
These break with pytest 8.4.0, see
https://docs.pytest.org/en/stable/changelog.html#pytest-8-4-0-2025-06-02

Fix the following errors in test_galaxy_packages tests:

```
FAILED tests/tool_shed/test_hg_util.py::test_add_file_and_commmit_changeset - Failed: Expected None, but test returned local('/tmp/pytest-of-runner/pytest-7/test_add_file_and_commmit_chan0/test.txt'). Did you mean to use `assert` instead of `return`?
FAILED tests/tool_shed/test_hg_util.py::test_add_dir_and_commit_changeset - Failed: Expected None, but test returned local('/tmp/pytest-of-runner/pytest-7/test_add_dir_and_commit_change0/abc'). Did you mean to use `assert` instead of `return`?
```

Also:
- Replace legacy `tmpdir` fixtures with `tmp_path`.
- Improve type annotations.