Fix async controller
Fixes https://sentry.galaxyproject.org/organizations/galaxy/issues/45939
```
AttributeError: 'HistoryDatasetAssociation' object has no attribute 'object_store_id'
  File "galaxy/web/framework/middleware/sentry.py", line 43, in __call__
    iterable = self.application(environ, start_response)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "galaxy/web/framework/middleware/statsd.py", line 35, in __call__
    req = self.application(environ, start_response)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "galaxy/web/framework/base.py", line 138, in __call__
    return self.handle_request(environ, start_response)
  File "galaxy/web/framework/base.py", line 217, in handle_request
    body = method(trans, **kwargs)
  File "galaxy/webapps/galaxy/controllers/async.py", line 153, in index
    data.dataset.object_store.create(data)
  File "galaxy/objectstore/__init__.py", line 297, in create
    return self._invoke('create', obj, **kwargs)
  File "galaxy/objectstore/__init__.py", line 291, in _invoke
    return self.__getattribute__(f"_{delegate}")(obj=obj, **kwargs)
  File "galaxy/objectstore/__init__.py", line 882, in _create
    if obj.object_store_id is None or not self._exists(obj, **kwargs):
```