Undo cceb5d27e1; temporary fix failing unit tests
3 unit tests failed with:
AttributeError: 'MockHda' object has no attribute '_sa_instance_state'
(Note/todo: this failure *may* have been due to the way the mock is setup.)