Catch all exception types when decoding an id
Under Python 3 `codecs.decode()` raises a `binascii.Error` exception instead
of a `TypeError`.
Fix the following traceback produced by the
`test/api/test_roles.py::RolesApiTestCase::test_show_error_codes`
API test under Python 3:

```
galaxy.web.framework.decorators ERROR 2018-08-22 22:17:47,960 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/galaxy_venv3/lib/python3.5/encodings/hex_codec.py", line 19, in hex_decode
    return (binascii.a2b_hex(input), len(input))
binascii.Error: Odd-length string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/galaxy/lib/galaxy/web/framework/decorators.py", line 157, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/galaxy/lib/galaxy/webapps/galaxy/api/roles.py", line 39, in show
    decoded_role_id = trans.security.decode_id(role_id)
  File "/galaxy/lib/galaxy/web/security/__init__.py", line 84, in decode_id
    return int(unicodify(id_cipher.decrypt(codecs.decode(obj_id, 'hex'))).lstrip("!"))
binascii.Error: decoding with 'hex' codec failed (Error: Odd-length string)
```

See https://jenkins.galaxyproject.org/job/docker-api-py3/140/testReport/junit/test.api.test_roles/RolesApiTestCase/test_show_error_codes/