Rework dependency shell command handling
The approach is to always log a warning with stdout and stderr when
the exit code is not 0.
With this change, one can expect logs like the follwing:
```
galaxy.tools.deps.conda_util DEBUG 2016-11-05 15:14:17,373 Executing command: /home/mvandenb/miniconda3/bin/conda create -y --name __bowtie@0.12.7 bowtie=0.12.7
127.0.0.1 - - [05/nov./2016:15:14:19 +0200] "POST /admin_toolshed/repository_installation_status_updates HTTP/1.1" 200 - "http://127.0.0.1:8080/admin_toolshed/prepare_for_install" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.90 Safari/537.36"
127.0.0.1 - - [05/nov./2016:15:14:22 +0200] "POST /admin_toolshed/repository_installation_status_updates HTTP/1.1" 200 - "http://127.0.0.1:8080/admin_toolshed/prepare_for_install" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.90 Safari/537.36"
galaxy.tools.deps.conda_util WARNING 2016-11-05 15:14:24,029 Failed to execute command-line /home/mvandenb/miniconda3/bin/conda create -y --name __bowtie@0.12.7 bowtie=0.12.7, stderr was:
-------->>begin stderr<<--------

PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels:
  - bowtie 0.12.7*

You can search for packages on anaconda.org with

    anaconda search -t conda bowtie

You may need to install the anaconda-client command line client with

    conda install anaconda-client

-------->>end stderr<<--------
-------->>begin stdout<<--------
Fetching package metadata ...............
Solving package specifications: .

-------->>end stdout<<--------

galaxy.tools.deps.resolvers.conda DEBUG 2016-11-05 15:14:24,030 Removing failed conda install of bowtie, version '0.12.7'
```
This should be helpful for the more obscure errors that can occur with conda.