Fix container resolution.
Without these decorators swapped - resolving containers results in the following Exception:

```
TypeError: unbound method __str__() must be called with ContainerResolver instance as first argument (got nothing instead)
```

I think this recent merge commit 3ed60db5ce9bf2acb954c843c14f8983b11ffbd9 introduced this problem as it merged the two decorators together.