Improve relabel identifiers message when number of columns is not 2
Fixes https://github.com/galaxyproject/galaxy/issues/18633:
```
ValueError: dictionary update sequence element #4 has length 1; 2 is required
  File "galaxy/tools/__init__.py", line 1969, in handle_single_execution
    rval = self.execute(
  File "galaxy/tools/__init__.py", line 2066, in execute
    return self.tool_action.execute(
  File "galaxy/tools/actions/model_operations.py", line 89, in execute
    self._produce_outputs(
  File "galaxy/tools/actions/model_operations.py", line 120, in _produce_outputs
    tool.produce_outputs(
  File "galaxy/tools/__init__.py", line 3816, in produce_outputs
    new_labels_dict = dict(source_new_label)

Exception caught while attempting to execute tool with id '__RELABEL_FROM_FILE__':
```