Fix create_db.sh
Broken in commit d34142e4203880393431d471a43b87e95980579e .

Traceback:

```
$ rm -f database/universe.sqlite && sqlite3 database/universe.sqlite 'VACUUM;' && ./create_db.sh
Activating virtualenv at .venv
Traceback (most recent call last):
  File "./scripts/create_db.py", line 44, in <module>
    invoke_create()
  File "./scripts/create_db.py", line 36, in invoke_create
    create_db(config['db_url'], config['config_file'])
  File "/opt/galaxy/lib/galaxy/model/migrate/check.py", line 74, in create_or_verify_database
    elif getattr(app.config, 'database_auto_migrate', False):
AttributeError: 'NoneType' object has no attribute 'config'
```