Fix test_singularity_container_test test
(which started failing since ubuntu-latest was moved to 24.04)
by upgrading apptainer to >=1.3.3 to include
https://github.com/apptainer/apptainer/pull/2262 .

Fix:

```
>       assert "samtools:1.0--1" in results["passed"], results
E       AssertionError:
E       {'failed': [{'commands': ['python -c "import pyBigWig; assert(pyBigWig.numpy '
E                                 '== 1); assert(pyBigWig.remote == 1)"'],
E                    'container': 'pybigwig:0.3.22--py36h54a71a5_0',
E                    'errors': [{'command': 'python -c "import pyBigWig; '
E                                           'assert(pyBigWig.numpy == 1); '
E                                           'assert(pyBigWig.remote == 1)"',
E                                'output': '\x1b[91mERROR  : Could not write info to '
E                                          'setgroups: Permission denied\n'
E                                          '\x1b[0m\x1b[91mERROR  : Error while '
E                                          'waiting event for user namespace mappings: '
E                                          'no event received\n'
E                                          '\x1b[0m'},
E                               {'import': 'pyBigWig',
E                                'output': '\x1b[91mERROR  : Could not write info to '
E                                          'setgroups: Permission denied\n'
E                                          '\x1b[0m\x1b[91mERROR  : Error while '
E                                          'waiting event for user namespace mappings: '
E                                          'no event received\n'
E                                          '\x1b[0m'}],
E                    'import_lang': 'python -c',
E                    'imports': ['pyBigWig']},
E                   {'commands': ['samtools view --help 2>&1 | grep Notes > /dev/null'],
E                    'container': 'samtools:1.0--1',
E                    'errors': [{'command': 'samtools view --help 2>&1 | grep Notes > '
E                                           '/dev/null',
E                                'output': '\x1b[91mERROR  : Could not write info to '
E                                          'setgroups: Permission denied\n'
E                                          '\x1b[0m\x1b[91mERROR  : Error while '
E                                          'waiting event for user namespace mappings: '
E                                          'no event received\n'
E                                          '\x1b[0m'}],
E                    'import_lang': 'python -c'}],
E        'notest': ['yasm:1.3.0--0'],
E        'passed': []}
E       assert 'samtools:1.0--1' in []
```

Also:
- Improve assertion messages to facilitate debugging