Reload built-in converters on toolbox reload
fixes #16947

also adds a setter to `MockApp` in order to fix the following
which was shown during tests

```
  /home/berntm/projects/galaxy/.venv/lib/python3.10/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-7 (check)

  Traceback (most recent call last):
    File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.10/threading.py", line 953, in run
      self._target(*self._args, **self._kwargs)
    File "/home/berntm/projects/galaxy/lib/galaxy/tool_util/toolbox/watcher.py", line 153, in check
      self.reload_callback()
    File "/home/berntm/projects/galaxy/lib/galaxy/app_unittest_utils/toolbox_support.py", line 44, in <lambda>
      app.watchers.tool_config_watcher.reload_callback = lambda: reload_callback(test_case)
    File "/home/berntm/projects/galaxy/lib/galaxy/app_unittest_utils/toolbox_support.py", line 193, in reload_callback
      test_case._toolbox = test_case.app.toolbox = SimplifiedToolBox(test_case)
  AttributeError: can't set attribute 'toolbox'

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
```