Cast ``url_for()`` output to ``str``
Starlette 0.26.0 has changed the return type of `HTTPConnection.url_for()`
from `str` to `URL`, which breaks the Galaxy package mypy tests:

```
mypy . --enable-incomplete-feature=Unpack
galaxy/webapps/galaxy/api/__init__.py:180: error: Incompatible types in
assignment (expression has type "str", variable has type "URL")  [assignment]
                    url = f"{url}?{urlencode(query_params)}"
                          ^
Found 1 error in 1 file (checked 255 source files)
```