Fixes for two error messages reported by @martenson.
One warning had an unexpanded template variable, the other error message was obsecured. Validation requires pykwalify, the error message now valiates this:

```
if [ -f .venv/bin/activate ]; then . .venv/bin/activate; fi; python scripts/config_manage.py validate reports
WARNING: Path [config/reports.yml] not a file, using sample.
Traceback (most recent call last):
  File "scripts/config_manage.py", line 505, in <module>
    main()
  File "scripts/config_manage.py", line 187, in main
    _validate(args, app_desc)
  File "scripts/config_manage.py", line 294, in _validate
    raise Exception("Cannot validate file, pykawlify is not installed.")
Exception: Cannot validate file, pykawlify is not installed.
make: *** [reports-config-validate] Error 1
```