Fix error reporting when input dataset is NoneType
The traceback is
```
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/jobs.py", line 184, in common_problems
    if input_dataset_instance.get_total_size() == 0:
AttributeError: 'NoneType' object has no attribute 'get_total_size'
```

... now it would be great to know when this happens, cause it looks
like it shouldn't happen at all.