Fix AttributeError in dataset display preview for non-string header value
Starlette requires all HTTP header values to be strings, but
`x-content-truncated` was set to an int (`max_peek_size`), causing
`AttributeError: 'int' object has no attribute 'encode'` when
previewing datasets larger than the max peek size.

Closes https://github.com/galaxyproject/galaxy/issues/22385
Fixes GALAXY-MAIN-4KSCZZZ0015FH