Retry conda `install` and `create` commands without strict channel priority
Restore the possibility to solve environments with packages present in
multiple channels but whose requested version is not available in the
highest priority one.
The issue applies only when using conda >=4.7.5.

Fix the following error for the
`test/integration/test_resolvers.py::TestCondaResolutionIntegration::test_dependency_install`
integration test:

```
____________ TestCondaResolutionIntegration.test_dependency_install ____________

self = <integration.test_resolvers.TestCondaResolutionIntegration object at 0x7f7009682950>

    def test_dependency_install(self):
        """
        Test installation of GNUPLOT dependency.
        """
        data = GNUPLOT
        create_response = self._post("dependency_resolvers/dependency", data=data, admin=True)
        self._assert_status_code_is(create_response, 200)
        response = create_response.json()
>       self._assert_dependency_type(response)

test/integration/test_resolvers.py:46:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <integration.test_resolvers.TestCondaResolutionIntegration object at 0x7f7009682950>
response = {'cacheable': False, 'dependency_resolver': {'auto_init': True, 'auto_install': False, 'can_uninstall_dependencies': T...nda,defaults', ...}, 'dependency_type': 'conda', 'environment_path': '/tmp/tmp5f_37kj2/conda/envs/__gnuplot@_uv_', ...}
type = 'conda', exact = True

    def _assert_dependency_type(self, response, type="conda", exact=True):
        if "dependency_type" not in response:
            raise Exception(f"Response [{response}] did not contain key 'dependency_type'")
        dependency_type = response["dependency_type"]
        assert dependency_type == type, f"Dependency type [{dependency_type}] not the expected value [{type}]"
        if "exact" not in response:
            raise Exception(f"Response [{response}] did not contain key 'exact'")
>       assert response["exact"] is exact
E       assert False is True

test/integration/test_resolvers.py:150: AssertionError
```

due to the fact that this test tries to install version 4.6 of gnuplot,
while in the highest priority conda-forge channel the oldest version
available is 5.0.5.
When trying to create the environment, conda fails to resolve it, so Galaxy
falls back to create an environment with an unversioned gnuplot, which fails
the exact version test.

Introduced in commit bb000b2403e51b2ecf2a4dfe9d2ac560b333a437 .