Show parameter name in DataToolParameter exception
Goal is to replace this kind of output in a failed test run:

RunToolException: Error creating a job for these tool inputs - Specify a dataset of the required format / build.

with:

RunToolException: Error creating a job for these tool inputs - Specify a dataset of the required format / build in parameter 'XXX'.