unicodify bytestrings from uwsgi.opt
Fix the 2 following tracebacks:

```
added lib/ to pythonpath.
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 180, in uwsgi_app
    return galaxy.web.framework.webapp.build_native_uwsgi_app(app_factory, "galaxy")
  File "lib/galaxy/web/framework/webapp.py", line 968, in build_native_uwsgi_app
    app_kwds = get_app_kwds(config_section)
  File "lib/galaxy/web/stack/__init__.py", line 434, in get_app_kwds
    return application_stack_class().get_app_kwds(config_section, app_name=app_name)
  File "lib/galaxy/web/stack/__init__.py", line 260, in get_app_kwds
    has_ini_config = has_ini_config or (config_file and has_ext(config_file, "ini", aliases=True, ignore="sample"))
  File "lib/galaxy/util/path/__init__.py", line 290, in has_ext
    root, _ext = __splitext_ignore(path, ignore=ignore)
  File "lib/galaxy/util/path/__init__.py", line 387, in __splitext_ignore
    root, ext = __splitext_no_sep(path)
  File "lib/galaxy/util/path/__init__.py", line 381, in __splitext_no_sep
    return (path.rsplit(extsep, 1) + [''])[0:2]
TypeError: a bytes-like object is required, not 'str'
unable to load app 0 (mountpoint='') (callable not found or import error)
```

```
galaxy.queue_worker INFO 2018-06-03 02:12:51,186 [p:2150,w:1,m:0] [MainThread] Binding and starting galaxy control worker for main.web.1
Traceback (most recent call last):
  File "lib/galaxy/web/stack/__init__.py", line 456, in _do_uwsgi_postfork
    f(*args, **kwargs)
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 190, in postfork_setup
    app.application_stack.log_startup()
  File "lib/galaxy/web/stack/__init__.py", line 351, in log_startup
    for s in UWSGIApplicationStack._serving_on():
  File "lib/galaxy/web/stack/__init__.py", line 237, in _serving_on
    yield UWSGIApplicationStack._socket_opt_to_str(opt, val)
  File "lib/galaxy/web/stack/__init__.py", line 208, in _socket_opt_to_str
    if val.startswith('='):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```