Pass `job` to `setup_external_metadata()` in `SetMetadataToolAction.execute_via_app()`
- Make `PortableDirectoryMetadataGenerator.setup_external_metadata()`
  resistant to missing `job`
- Get `job` only once in
  `JobExternalOutputMetadataWrapper.setup_external_metadata()`

Fix the following traceback:
```
Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/web/framework/decorators.py", line 305, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/webapps/galaxy/api/history_contents.py", line 654, in update
    return self.__update_dataset(trans, history_id, id, payload, **kwd)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/webapps/galaxy/api/history_contents.py", line 691, in __update_dataset
    self.__deserialize_dataset(hda, payload, trans)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/webapps/galaxy/api/history_contents.py", line 718, in __deserialize_dataset
    self.hda_deserializer.deserialize(hda, payload, user=trans.user, trans=trans)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/managers/base.py", line 740, in deserialize
    new_dict[key] = self.deserializers[key](item, key, val, **context)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/managers/datasets.py", line 690, in deserialize_datatype
    self.app.datatypes_registry.set_external_metadata_tool.tool_action.execute(self.app.datatypes_registry.set_external_metadata_tool, trans, incoming={'input1': item}, overwrite=False)  # overwrite is False as per existing behavior
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/tools/actions/metadata.py", line 29, in execute
    overwrite, history, job_params)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/tools/actions/metadata.py", line 108, in execute_via_app
    kwds={'overwrite': overwrite})
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/metadata/__init__.py", line 158, in setup_external_metadata
    "job_id_tag": job.get_id_tag(),
AttributeError: 'NoneType' object has no attribute 'get_id_tag'
```