Fix ``GiHttpMixin`` by passing API key in request headers
Fix the following traceback when running `./scripts/cwl-runner` in
the cwl-1.0 branch:

```
Traceback (most recent call last):
  File "./scripts/run_cwl.py", line 98, in <module>
    main()
  File "./scripts/run_cwl.py", line 86, in main
    run = cwl_populator.run_cwl_job(tool, job)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/lib/galaxy_test/base/populators.py", line 2091, in run_cwl_job
    history_id = self.dataset_populator.new_history()
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/lib/galaxy_test/base/populators.py", line 752, in new_history
    assert "id" in create_history_response.json(), create_history_response.text
AssertionError: {"err_msg":"You need to be logged in to create histories.","err_code":403001}
```