fix metadata setting for empty tiff files
had a tool that created (by error) an empty tiff file:

```
galaxy.metadata DEBUG 2024-07-11 09:42:55,503 [pN:main.3,p:97809,tN:SlurmRunner.work_thread-2] setting metadata externally failed for HistoryDatasetAssociation 903743: Traceback (most recent call last):
  File "/data/galaxy_server/galaxy/.venv/lib/python3.11/site-packages/tifffile/tifffile.py", line 4053, in __init__
    byteorder = {b'II': '<', b'MM': '>', b'EP': '<'}[header[:2]]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: b''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/metadata/set_metadata.py", line 518, in set_metadata_portable
    set_meta(dataset, file_dict)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/metadata/set_metadata.py", line 205, in set_meta
    set_meta_with_tool_provided(
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/metadata/set_metadata.py", line 141, in set_meta_with_tool_provided
    dataset_instance.datatype.set_meta(dataset_instance, **set_meta_kwds)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/datatypes/images.py", line 113, in set_meta
    with tifffile.TiffFile(dataset.get_file_name()) as tif:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/galaxy_server/galaxy/.venv/lib/python3.11/site-packages/tifffile/tifffile.py", line 4055, in __init__
    raise TiffFileError(f'not a TIFF file {header!r}') from exc
tifffile.tifffile.TiffFileError: not a TIFF file b''

galaxy.jobs.runners ERROR 2024-07-11 09:42:55,509 [pN:main.3,p:97809,tN:SlurmRunner.work_thread-2] (261108/23547903) Job wrapper finish method failed
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.11/site-packages/tifffile/tifffile.py", line 4053, in __init__
    byteorder = {b'II': '<', b'MM': '>', b'EP': '<'}[header[:2]]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: b''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/jobs/runners/__init__.py", line 656, in _finish_or_resubmit_job
    job_wrapper.finish(
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/jobs/__init__.py", line 1967, in finish
    self._finish_dataset(output_name, dataset, job, context, final_job_state, remote_metadata_directory)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/jobs/__init__.py", line 1778, in _finish_dataset
    dataset.datatype.set_meta(dataset, overwrite=False)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/datatypes/images.py", line 113, in set_meta
    with tifffile.TiffFile(dataset.get_file_name()) as tif:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/.venv/lib/python3.11/site-packages/tifffile/tifffile.py", line 4055, in __init__
    raise TiffFileError(f'not a TIFF file {header!r}') from exc
tifffile.tifffile.TiffFileError: not a TIFF file b''
```