Fix `GET /api/whoami` when last_password_change is NULL
Fix the following traceback:

```
  File "/srv/galaxy/.venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/srv/galaxy/lib/galaxy/webapps/galaxy/api/configuration.py", line 53, in whoami
    return _user_to_model(trans.user, trans.security)
  File "/srv/galaxy/lib/galaxy/webapps/galaxy/api/configuration.py", line 123, in _user_to_model
    return UserModel(**user.to_dict(view="element", value_mapper={"id": security.encode_id})) if user else None
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for UserModel
last_password_change
  none is not an allowed value (type=type_error.none.not_allowed)
```