Update Python dependencies
Disallow python-irodsclient 1.1.2 due to

https://github.com/irods/python-irodsclient/issues/356

which breaks several integration tests with:

```
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/irods/message/__init__.py", line 163, in _recv_message_in_len
    host, port = sock.getpeername()
ValueError: too many values to unpack (expected 2)
```