Fix circster launch and saving
Fixes:
```
Error - <class 'binascii.Error'>: decoding with 'hex' codec failed (Error: Odd-length string)
URL: http://127.0.0.1:8080/visualization/circster?id=undefined
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/middleware/error.py', line 154 in __call__
  app_iter = self.application(environ, sr_checker)
File '/Users/mvandenb/src/galaxy/.venv/lib/python3.6/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/Users/mvandenb/src/galaxy/.venv/lib/python3.6/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/base.py', line 143 in __call__
  return self.handle_request(environ, start_response)
File '/Users/mvandenb/src/galaxy/lib/galaxy/web/framework/base.py', line 222 in handle_request
  body = method(trans, **kwargs)
File '/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/controllers/visualization.py', line 764 in circster
  vis = self.get_visualization(trans, id, check_ownership=False, check_accessible=True)
File '/Users/mvandenb/src/galaxy/lib/galaxy/webapps/base/controller.py', line 651 in get_visualization
  visualization = trans.sa_session.query(trans.model.Visualization).get(trans.security.decode_id(id))
File '/Users/mvandenb/src/galaxy/lib/galaxy/security/idencoding.py', line 84 in decode_id
  return int(unicodify(id_cipher.decrypt(codecs.decode(obj_id, 'hex'))).lstrip("!"))
Error: decoding with 'hex' codec failed (Error: Odd-length string)
```
among other things. This happens when a new circster instance is created
and it doens't have an id yet. `id` then is `undefined`, which is not a
valid id.