Fix refresh token expiration retrieval logic
Fixes traceback when refresh_token is None:
Oct 31 01:14:47 dev galaxyctl[3357277]: Traceback (most recent call last):
Oct 31 01:14:47 dev galaxyctl[3357277]:   File "/mnt/galaxy/galaxy-app/lib/galaxy/authnz/managers.py", line 306, in refresh_expiring_oidc_tokens_for_provider
Oct 31 01:14:47 dev galaxyctl[3357277]:     refreshed = backend.refresh(trans, auth)
Oct 31 01:14:47 dev galaxyctl[3357277]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 31 01:14:47 dev galaxyctl[3357277]:   File "/mnt/galaxy/galaxy-app/lib/galaxy/authnz/psa_authnz.py", line 206, in refresh
Oct 31 01:14:47 dev galaxyctl[3357277]:     expires = self._try_to_locate_refresh_token_expiration(user_authnz_token.extra_data)
Oct 31 01:14:47 dev galaxyctl[3357277]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 31 01:14:47 dev galaxyctl[3357277]:   File "/mnt/galaxy/galaxy-app/lib/galaxy/authnz/psa_authnz.py", line 228, in _try_to_locate_refresh_token_expiration
Oct 31 01:14:47 dev galaxyctl[3357277]:     or extra_data["refresh_token"].get("expires", None)
Oct 31 01:14:47 dev galaxyctl[3357277]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 31 01:14:47 dev galaxyctl[3357277]: AttributeError: 'NoneType' object has no attribute 'get'