Fix error or loading internal tool `SIFT`
Error popping up all the time:

```
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tool_util/toolbox/base.py", line 873, in _load_tool_tag_set
    tool = self.load_tool(concrete_path, use_cached=False, tool_cache_data_dir=tool_cache_data_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tool_util/toolbox/base.py", line 1100, in load_tool
    tool = self.create_tool(
           ^^^^^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/__init__.py", line 547, in create_tool
    return self._create_tool_from_source(tool_source, config_file=config_file, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/__init__.py", line 563, in _create_tool_from_source
    return create_tool_from_source(self.app, tool_source, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/__init__.py", line 355, in create_tool_from_source
    tool = ToolClass(config_file, tool_source, app, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/__init__.py", line 820, in __init__
    raise e
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/__init__.py", line 817, in __init__
    self.parse(tool_source, guid=guid, dynamic=dynamic)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/__init__.py", line 1142, in parse
    self.parse_inputs(self.tool_source)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/__init__.py", line 1427, in parse_inputs
    inputs = self.parse_input_elem(page_source, enctypes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/__init__.py", line 1622, in parse_input_elem
    param = self.parse_param_elem(input_source, enctypes, context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/__init__.py", line 1635, in parse_param_elem
    param = ToolParameter.build(self, input_source)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/parameters/basic.py", line 330, in build
    return parameter_types[param_type](tool, input_source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/parameters/basic.py", line 2071, in __init__
    super().__init__(tool, input_source, trans)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/parameters/basic.py", line 1863, in __init__
    super().__init__(tool, input_source)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/parameters/basic.py", line 186, in __init__
    self.validators.append(validation.Validator.from_element(self, elem))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/parameters/validation.py", line 45, in from_element
    return validator_types[_type].from_element(param, elem)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/parameters/validation.py", line 399, in from_element
    assert os.path.exists(filename), f"File {filename} specified by the 'filename' attribute not found"
AssertionError: File /gpfs1/data/galaxy_server/galaxy/tool-data/sift_db.loc specified by the 'filename' attribute not found
```

I think using the other validator should not cause so much trouble.