Avoid exception when opening apply rules tool and no collection in history
Fixes https://sentry.galaxyproject.org/share/issue/97b5b9cfcef14ca0b59b851684170698/
```
AttributeError: 'NoneType' object has no attribute 'id'
  File "galaxy/tools/__init__.py", line 2601, in populate_model
    tool_dict = input.to_dict(request_context, other_values=other_values)
  File "galaxy/tools/parameters/basic.py", line 2648, in to_dict
    "id": trans.app.security.encode_id(target.id),
```

Which is in a try/except anyway, so fairly inconsequential, but results
in cleaner logs / one less sentry error.