Move definition of ``DatasetCollectionDescriptionT`` before its use
Fix the following error on py37-test_galaxy_packages_for_pulsar tests:

```
FAILED tests/tool_util/test_input_models.py::test_input_collection_type - pydantic.errors.PydanticUserError: `ParsedTool` is not fully defined; you should define `DatasetCollectionDescriptionT`, then call `ParsedTool.model_rebuild()`.
```

Also:
- Removed unused types:
  - `IncomingNotRequiredDatasetCollectionDescriptionT`
  - `IncomingNotRequiredDatasetCollectionDescription`
  - `IncomingToolOutputBaseModel`