Register job data when testing a tool with missing input file
Running `planemo test` for a tool for which an input file is missing
from the `test-data` directory results in the following traceback:

```
There were problems with 1 test(s) - out of 1 test(s) executed. See /usr/users/ga002/soranzon/software/nsoranzo_isatools-galaxy/tool_test_output.html for detailed breakdown.
Traceback (most recent call last):
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/planemo/test/results.py", line 115, in get_dict_value
    return data[key]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/bin/planemo", line 10, in <module>
    sys.exit(planemo())
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/planemo/cli.py", line 189, in handle_blended_options
    return f(*args, **kwds)
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/planemo/commands/cmd_test.py", line 93, in cli
    return_value = run_in_config(ctx, config, **kwds)
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/planemo/galaxy/test/actions.py", line 118, in run_in_config
    kwds=kwds
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/planemo/galaxy/test/actions.py", line 132, in handle_reports_and_summary
    **kwds
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/planemo/galaxy/test/actions.py", line 223, in _handle_summary
    **kwds
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/planemo/galaxy/test/actions.py", line 235, in _summarize_tests_full
    _summarize_test_case(test_case_data, **kwds)
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/planemo/galaxy/test/actions.py", line 254, in _summarize_test_case
    get_dict_value("data", structured_data)
  File "/usr/users/ga002/soranzon/software/nsoranzo_planemo/.venv3/lib/python3.6/site-packages/planemo/test/results.py", line 117, in get_dict_value
    raise KeyError("No key [%s] in [%s]" % (key, data))
KeyError: 'No key [status] in [None]'
```

This is fixed by moving the `stage_data_in_history()` call inside the
try/finally block.

Fix https://github.com/galaxyproject/planemo/issues/942 .