Fix traceback in ``printquery()``
Fix the following traceback:

```
/usr/users/ga002/soranzon/software/galaxyproject_galaxy/scripts/db_shell.py in printquery(statement, bind)
     60         if bind is None:
     61             bind = statement.session.get_bind(
---> 62                 statement._mapper_zero_or_none())
     63         statement = statement.statement
     64     elif bind is None:

AttributeError: 'Query' object has no attribute '_mapper_zero_or_none'
```

due to the removal of `_mapper_zero_or_none()` in SQLAlchemy commit
https://github.com/sqlalchemy/sqlalchemy/commit/234a5b9723fbbb9747c0f9e3917baf8500b73370