Use ``best_search_result()`` function instead of parsing anaconda.org web pages
Fix the following mulled unit test:

```
FAILED test/unit/tool_util/mulled/test_get_tests.py::test_hashed_test_search - AssertionError: assert ['samtools --help'] == ['bamtools --help', 'samtools --help']
  At index 0 diff: 'samtools --help' != 'bamtools --help'
  Right contains one more item: 'samtools --help'
  Full diff:
  - ['bamtools --help', 'samtools --help']
  + ['samtools --help']
```

that started not finding bamtools-2.4.0 inside
https://anaconda.org/bioconda/bamtools/files any more.

Also:
- Add type annotation to `CondaInDockerContext` and fix ensuing issues.