Add missing pin for `rich`, dependency of refgenconf 0.12.0
Pinning to the version that was current when
https://github.com/galaxyproject/galaxy/pull/12435
was merged to fix the following traceback with rich 12.1.0:

```
2022-04-04T14:16:19.5073158Z   File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/tools/data/__init__.py", line 21, in <module>
2022-04-04T14:16:19.5073535Z     import refgenconf
2022-04-04T14:16:19.5074393Z   File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/refgenconf/__init__.py", line 6, in <module>
2022-04-04T14:16:19.5074853Z     from .populator import looper_refgenie_populate
2022-04-04T14:16:19.5075535Z   File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/refgenconf/populator.py", line 9, in <module>
2022-04-04T14:16:19.5075970Z     from . import refgenconf
2022-04-04T14:16:19.5076607Z   File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 27, in <module>
2022-04-04T14:16:19.5077091Z     from rich.progress import BarColumn, Progress, TextColumn
2022-04-04T14:16:19.5077768Z   File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/rich/progress.py", line 43, in <module>
2022-04-04T14:16:19.5078272Z     from .console import Console, JustifyMethod, RenderableType, Group
2022-04-04T14:16:19.5078956Z   File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/rich/console.py", line 46, in <module>
2022-04-04T14:16:19.5079437Z     from ._log_render import FormatTimeCallable, LogRender
2022-04-04T14:16:19.5080105Z   File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/rich/_log_render.py", line 5, in <module>
2022-04-04T14:16:19.5124479Z     from .text import Text, TextType
2022-04-04T14:16:19.5130069Z   File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/rich/text.py", line 5, in <module>
2022-04-04T14:16:19.5134858Z     from rich.emoji import EmojiVariant
2022-04-04T14:16:19.5139847Z   File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/rich/emoji.py", line 4, in <module>
2022-04-04T14:16:19.5144648Z     from .jupyter import JupyterMixin
2022-04-04T14:16:19.5147478Z   File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/rich/jupyter.py", line 4, in <module>
2022-04-04T14:16:19.5150060Z     from .segment import Segment
2022-04-04T14:16:19.5152862Z   File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/rich/segment.py", line 19, in <module>
2022-04-04T14:16:19.5155442Z     from .cells import (
2022-04-04T14:16:19.5158112Z   File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/rich/cells.py", line 6, in <module>
2022-04-04T14:16:19.5159612Z     from ._lru_cache import LRUCache
2022-04-04T14:16:19.5161691Z   File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/rich/_lru_cache.py", line 8, in <module>
2022-04-04T14:16:19.5163233Z     from typing_extensions import OrderedDict
2022-04-04T14:16:19.5165289Z ImportError: cannot import name 'OrderedDict' from 'typing_extensions' (/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/typing_extensions.py)
```