Pin pygithub to 1.54.  Resolves conflicting dependency resolution below:
INFO: pip is looking at multiple versions of adal to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r ./lib/galaxy/dependencies/dev-requirements.txt (line 37), adal==1.2.5 and pyjwt==2.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pyjwt==2.0.1
    The user requested pyjwt==2.0.1
    adal 1.2.5 depends on PyJWT>=1.0.0
    pygithub 1.54.1 depends on pyjwt<2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies