More specific type annotation for ``BaseJobExec.parse_status()``
Add type annotation to ``BaseJobExec.parse_single_status()``

Follow-up on https://github.com/galaxyproject/galaxy/pull/17367#discussion_r1469748812 .

Needed to add ``TypeAlias`` to ``model.Job.states`` to fix:

```
lib/galaxy/jobs/runners/util/cli/job/__init__.py:67: error: Variable "galaxy.jobs.runners.util.cli.job.job_states" is not valid as a type  [valid-type]
        def parse_status(self, status: str, job_ids: List[str]) -> Dict[str, job_states]:
                                                                             ^
```

See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases :

> You should always use ``TypeAlias`` to define a type alias in a class body
> or inside a function.