Don't fail startup if monitored tool not installed anymore
Fixes
```
galaxy.jobs.handler WARNING 2023-04-05 12:33:46,660 [pN:main,p:6422,tN:MainThread] (42544) Tool 'toolshed.g2.bx.psu.edu/repos/iuc/trinity/trinity/2.9.1+galaxy2' removed from tool config, unable to recover job
galaxy.jobs DEBUG 2023-04-05 12:33:46,666 [pN:main,p:6422,tN:MainThread] (42544) fail(): Job destination raised JobMappingException('Can't map job to destination, tool 'toolshed.g2.bx.psu.edu/repos/iuc/trinity/trinity/2.9.1+galaxy2' is unavailable'), caching fake '__fail__' destination for completion of fail method
Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/webapps/galaxy/buildapp.py", line 59, in app_pair
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/app.py", line 714, in __init__
    self.application_stack.register_postfork_function(self.job_manager.start)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/web_stack/__init__.py", line 46, in register_postfork_function
    f(*args, **kwargs)
  File "/Users/mvandenb/src/galaxy/lib/galaxy/jobs/manager.py", line 41, in start
    self.job_handler.start()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/jobs/handler.py", line 93, in start
    self.job_queue.start()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/jobs/handler.py", line 248, in start
    self.__check_jobs_at_startup()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/jobs/handler.py", line 295, in __check_jobs_at_startup
    self.job_wrapper(job).fail(
  File "/Users/mvandenb/src/galaxy/lib/galaxy/jobs/__init__.py", line 1416, in fail
    for dataset_path in self.job_io.get_output_fnames():
  File "/Users/mvandenb/src/galaxy/lib/galaxy/jobs/__init__.py", line 1069, in job_io
    tool_directory=self.tool_directory(),
  File "/Users/mvandenb/src/galaxy/lib/galaxy/jobs/__init__.py", line 1050, in tool_directory
    tool_dir = self.tool.tool_dir
AttributeError: 'NoneType' object has no attribute 'tool_dir'
```