Fix test_deserialize_* unit tests
Fix:

```
    def test_deserialize_xml_tool(tool_app):

>       tool = _deserialize(tool_app, tool_source_class='XmlToolSource', raw_tool_source=XML_TOOL)

test/unit/app/tools/test_tool_deserialization.py:59:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/unit/app/tools/test_tool_deserialization.py:54: in _deserialize
    return create_tool_from_source(app, tool_source=tool_source)
lib/galaxy/tools/__init__.py:278: in create_tool_from_source
    tool = ToolClass(config_file, tool_source, app, **kwds)
lib/galaxy/tools/__init__.py:606: in __init__
    raise e
lib/galaxy/tools/__init__.py:603: in __init__
    self.parse(tool_source, guid=guid, dynamic=dynamic)

        if has_missing_data:
            biotools_reference = self.biotools_reference
>           metadata_source = self.app.biotools_metadata_source
E           AttributeError: 'ToolApp' object has no attribute 'biotools_metadata_source'

lib/galaxy/tools/__init__.py:1032: AttributeError
```

introduced merging forward https://github.com/galaxyproject/galaxy/pull/13202 .