Fix pages encoding.  Using str on previously unicodify'd extended set values does not work.
```
In [2]: str("Blah blah blah, this breaks the page: ಠ_ಠ")
Out[2]: 'Blah blah blah, this breaks the page:
\xe0\xb2\xa0_\xe0\xb2\xa0'

In [3]: str(unicodify("Blah blah blah, this breaks the page: ಠ_ಠ"))
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call
last)
<ipython-input-3-4a83f5e5f5c8> in <module>()
----> 1 str(unicodify("Blah blah blah, this breaks the page: ಠ_ಠ"))

UnicodeEncodeError: 'ascii' codec can't encode character u'\u0ca0' in
position 38: ordinal not in range(128)
```