Update requirements of sort1 tool
Otherwise the conda environment for it fails to solve with the following
error:

```
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package grep-2.14-h470a237_2 is excluded by strict repo priority
```

This is due to the fact that grep 2.14 is only available on the bioconda
channel, while newer versions are on conda-forge, which has a higher
priority.

Reported by @mvdbeek in https://github.com/galaxyproject/galaxy/pull/20876/files#r2336209775 .