Fix traceback when exporting a workflow as BioCompute Object
Fallback to tool id if a workflow step doesn't have a label. Fix:

```
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 1456, in export_invocation_bco
    bco = self._deprecated_generate_bco(trans, invocation_id, merge_history_metadata)
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 1509, in _deprecated_generate_bco
    return self.invocations_service.deprecated_generate_invocation_bco(trans, invocation_id, export_options)
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/webapps/galaxy/services/invocations.py", line 229, in deprecated_generate_invocation_bco
    export_target.seek(0)
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/model/store/__init__.py", line 2146, in __exit__
    self._finalize()
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/model/store/__init__.py", line 2274, in _finalize
    core_biocompute_object, object_id = self._core_biocompute_object_and_object_id()
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/model/store/__init__.py", line 2362, in _core_biocompute_object_and_object_id
    pipeline_step = PipelineStep(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PipelineStep
name
  none is not an allowed value (type=type_error.none.not_allowed)
```