Catch datatype converion exception and return proper error
Fixes
https://sentry.galaxyproject.org/organizations/galaxy/issues/45438:
```
Exception: A converter does not exist for tsv to tabular.
  File "galaxy/web/framework/decorators.py", line 312, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "galaxy/webapps/galaxy/controllers/dataset.py", line 393, in set_edit
    message = data.datatype.convert_dataset(trans, data, target_type)
  File "galaxy/datatypes/data.py", line 641, in convert_dataset
    raise Exception(f"A converter does not exist for {original_dataset.ext} to {target_type}.")
```
which ... is not a valid option in the user interface, but I assume this
can happen if you change the datatype in another browser tab.