Add missing ending newline to test.sig test data file
Broken in https://github.com/galaxyproject/galaxy/pull/21473 .

Fix the following integration test issue:

```
FAILED test/integration/test_datatype_upload.py::test_upload_datatype_auto[test.sig] - AssertionError: Expected md5 sum 'fbbf5dc7ef17afae88808dc081dcc00b' for lib/galaxy/datatypes/test/test.sig, but test file md5sum is 44253008a9d105332ed107199fceb4d8. You need to add a final newline to lib/galaxy/datatypes/test/test.sig.
assert 'fbbf5dc7ef17afae88808dc081dcc00b' == '44253008a9d105332ed107199fceb4d8'
  - 44253008a9d105332ed107199fceb4d8
  + fbbf5dc7ef17afae88808dc081dcc00b
```