Fix dataset controller actions
We don't have a parent property anymore.
That's been broken since 21.09.
Fixes
https://sentry.galaxyproject.org/organizations/galaxy/issues/4971/?project=3&query=is%3Aunresolved&statsPeriod=14d:

```
AttributeError: 'HistoryDatasetAssociation' object has no attribute 'parent'
  File "galaxy/webapps/galaxy/controllers/dataset.py", line 897, in _undelete
    while topmost_parent.parent:
```