Fix ``get_test_from_anaconda()`` and ``base_image_for_targets()`` functions
by extracting all specified files in ``get_files_from_conda_package()``
and processing them in order of precedence.

Fix broken mulled unit test:

```
FAILED test/unit/tool_util/mulled/test_get_tests.py::test_hashed_test_search - AssertionError: assert ['bamtools --help'] == ['bamtools --help', 'samtools --help']
  Right contains one more item: 'samtools --help'
  Full diff:
  - ['bamtools --help', 'samtools --help']
  + ['bamtools --help']
```

which failed because, after a new build of samtools 1.3.1 was released,
``get_file_from_conda_package()`` started returning the content of
``info/recipe/meta.yaml.template`` instead of ``info/recipe/meta.yaml``
when called inside ``get_test_from_anaconda()``. Then parsing
the content of ``info/recipe/meta.yaml.template`` in
``get_commands_from_yaml()`` failed with

```
jinja2.exceptions.UndefinedError: 'compiler' is undefined
```

because that file contains ``{{ compiler('c') }}`` .

Broken in https://github.com/galaxyproject/galaxy/pull/15682 .