Fix vue typescript error around tags.
src/components/History/Layout/DetailsLayout.vue:100:9 - error TS2322: Type 'string[] | undefined' is not assignable to type 'string[]'.
  Type 'undefined' is not assignable to type 'string[]'.

100         tags: props.tags,
            ~~~~

  src/components/History/Layout/DetailsLayout.vue:47:67
    47 const localProps = ref<{ name: string; annotation: string | null; tags: string[] }>({
                                                                         ~~~~
    The expected type comes from property 'tags' which is declared here on type '{ name: string; annotation: string | null; tags: string[]; }'