Move definition of DatasetCollectionDescriptionT before its use
Fix the following error on py37-test_galaxy_packages_for_pulsar tests:

```
FAILED tests/tool_util/test_input_models.py::test_input_collection_type - pydantic.errors.PydanticUserError: `ParsedTool` is not fully defined; you should define `DatasetCollectionDescriptionT`, then call `ParsedTool.model_rebuild()`.
```

Backport of commit bb87560d8f45f0219e179a0da3e65de0e522ae89 .