Delay tool form rendering until config is loaded
The config typically is already loaded once you hit the tool form,
so this shouldn't cause a delay, and we already do the same effectively
for the current user and current history id.

Fixes https://github.com/galaxyproject/galaxy/issues/18139
```
TypeError: e.config is null
  at $b (webpack://@galaxyproject/galaxy-client/./src/components/Tool/ToolForm.vue?5639:1:1709)
  at Vue.prototype._render (webpack://@galaxyproject/galaxy-client/./node_modules/vue/dist/vue.esm.js:2540:28)
  at updateComponent (webpack://@galaxyproject/galaxy-client/./node_modules/vue/dist/vue.esm.js:2980:27)
  at Watcher.prototype.get (webpack://@galaxyproject/galaxy-client/./node_modules/vue/dist/vue.esm.js:4164:33)
  at Watcher.prototype.run (webpack://@galaxyproject/galaxy-client/./node_modules/vue/dist/vue.esm.js:4240:30)
...
(3 additional frame(s) were not displayed)
```