Add missing ``unittest_utils`` package to galaxy-tool-util
Fix:

```
ModuleNotFoundError: No module named 'galaxy.tool_util.unittest_utils'
```

in https://github.com/conda-forge/galaxy-tool-util-feedstock/pull/4 .