Patch LargeBinary to cast strings to bytestring
I don't fully understand the issue, and we might be accumulating
technical debt here. What I'm seeing without this commit is this
when I run for instance the VisualizationsApiTestCase.test_create
API test.

```
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/web/framework/decorators.py", line 283, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/galaxy/lib/galaxy/webapps/galaxy/api/visualizations.py", line 55, in index
    visualizations = self.get_visualizations_by_user(trans, user)
  File "/galaxy/lib/galaxy/web/base/controller.py", line 664, in get_visualizations_by_user
    return query.all()
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2737, in all
    return list(self)
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 98, in instances
    util.raise_from_cause(err)
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 79, in instances
    rows = [proc(row) for row in fetch]
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 79, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 493, in _instance
    loaded_instance, populate_existing, populators)
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 604, in _populate_full
    populator(state, dict_, row)
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 1782, in load_scalar_from_joined_new_row
    dict_[key] = _instance(row)
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 493, in _instance
    loaded_instance, populate_existing, populators)
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 593, in _populate_full
    dict_[key] = getter(row)
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/sql/type_api.py", line 1204, in process
    return process_value(impl_processor(value), dialect)
  File "/galaxy_venv3/lib/python3.5/site-packages/sqlalchemy/sql/sqltypes.py", line 902, in process
    value = bytes(value)
TypeError: string argument without an encoding
```

I think LargeBinary isn't meant to store strings the way we do this (we
dump JSON as bytestring), and somehow on python 3 we get unicode strings
back from the database, which blows up here. I suspect this might be
configured on the connection level (see
http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#unicode),
but not blowing up here seems like a good default.