Fix type error around history click to edit name.
src/components/History/Layout/DetailsLayout.vue:124:17 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

124                 v-model="clickToEditName"
                    ~~~~~~~

  src/components/Collections/common/ClickToEdit.vue:8:5
    8     value: string;
          ~~~~~
    The expected type comes from property 'value' which is declared here on type 'Readonly<Partial<{}> & Omit<Readonly<ExtractPropTypes<__VLS_TypePropsToOption<Props>>>, never>> & Record<...>'