Improved Selenium exception messages.
For many common waiting operations used throughout many tests:

```
TimeoutException: Message:
```

Will become something like

```
TimeoutException: Message: Timeout waiting on CSS selector [#dataset-adb5f5c93f827949.state-failed] to become visible.
```

For HID waiting I've added the state and HID as well - so something like this:

```
TimeoutException: Message: Failed waiting on history item 1 state to change to [ok] current state [failed]. Timeout waiting on CSS selector [#dataset-adb5f5c93f827949.state-failed] to become visible.
```