Fix virtualenv activation for some scripts
In particular add virtualenv activation to extract_dataset_parts.sh
to fix the following error when running tools which use
`<parallelism>`:
```
Fatal error:
/tmp/tmpOoQ01k/job_working_directory/000/12/task_0:
Traceback (most recent call last):
File "./scripts/extract_dataset_part.py", line 17, in <module>
import galaxy.model.mapping  # need to load this before we unpickle, in order to setup properties assigned by the mappers
File "/opt/galaxyproject_galaxy_release_17.05/lib/galaxy/model/__init__.py", line 20, in <module>
from six import string_types
ModuleNotFoundError: No module named 'six'
```