Drop use of deprecated ``method`` parameter of starlette ``FileResponse``
Removed in starlette 1.0, see https://github.com/Kludex/starlette/pull/3147

Fix the following mypy errors in package tests:

```
galaxy/webapps/base/api.py:94: error: Too many arguments for "__init__" of
"FileResponse"  [call-arg]
            super().__init__(
            ^~~~~~~~~~~~~~~~~
galaxy/webapps/base/api.py:95: error: Argument 8 to "__init__" of
"FileResponse" has incompatible type "str | None"; expected "str"  [arg-type]
    ..., media_type, background, filename, stat_result, method, content_dispo...
                                                        ^~~~~~
```