Catch exceptions when job.user is None
prevents the following error:

galaxy.web.framework.decorators ERROR 2022-01-17 14:52:09,619 [p:18,w:1,m:0] [uWSGIWorker1Core1] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/jobs.py", line 113, in index
    j['user_email'] = job.user.email
AttributeError: 'NoneType' object has no attribute 'email'