Fix ``TestJobFilesIntegration`` initialization
`input_hda_dict` and `input_hda` are initialized once for all tests
in the class, i.e. they needed to be class attributes.

Fix the following error when running all tests in the class with
`./run_tests.sh -integration test/integration/test_job_files.py`:

```
self = <integration.test_job_files.TestJobFilesIntegration object at 0x73c52a002260>

    def test_read_fails_if_input_file_purged(self):
        job, _, _ = self.create_static_job_with_state("running")
        job_id, job_key = self._api_job_keys(job)
>       input_file_path = self.input_hda.get_file_name()
E       AttributeError: 'TestJobFilesIntegration' object has no attribute 'input_hda'
```