Fix as_ucsc_display_file
Should fix https://sentry.galaxyproject.org/sentry/main/issues/501237/:
```
TypeError: a bytes-like object is required, not 'str'
  File "galaxy/datatypes/data.py", line 625, in as_display_type
    return getattr(self, self.supported_display_apps[type]['file_function'])(dataset, **kwd)
  File "galaxy/datatypes/interval.py", line 446, in as_ucsc_display_file
    return Interval.as_ucsc_display_file(self, dataset)
  File "galaxy/datatypes/interval.py", line 225, in as_ucsc_display_file
    fh.write('%s\n' % '\t'.join(tmp))
  File "python3.6/tempfile.py", line 485, in func_wrapper
    return func(*args, **kwargs)
```