Allow #if $datasets #end if patern for file lists
Otherwise the following exception occurs:
```
Traceback (most recent call last):
  File "/home/wolffj/src/galaxy/lib/galaxy/jobs/runners/__init__.py", line 191, in prepare_job
    job_wrapper.prepare()
  File "/home/wolffj/src/galaxy/lib/galaxy/jobs/__init__.py", line 858, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/home/wolffj/src/galaxy/lib/galaxy/tools/evaluation.py", line 435, in build
    raise e
AttributeError: 'DatasetListWrapper' object has no attribute 'value'
```

This is because DatasetListWrapper inherits `__bool__` from ToolParameterValueWrapper
which defines bool as
```
    def __bool__(self):
        return bool(self.value)
    __nonzero__ = __bool__
```
while DatasetListWrapper has no `value` attribute.

Fixes https://github.com/galaxyproject/galaxy/issues/6314 reported by
@joachimwolff (many thanks for the detailed report!).