Set correct status code in old history route
`err_code.code` is our internal error, more specific code that looks
like `403003` for instance, while we need to set a standard webob.exc
status code here.

Fixes https://sentry.galaxyproject.org/sentry/test/issues/1216796/:
```
AttributeError: 'NoneType' object has no attribute 'code'
  File "galaxy/web/framework/middleware/sentry.py", line 43, in __call__
    iterable = self.application(environ, start_response)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.6/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "galaxy/web/framework/middleware/statsd.py", line 33, in __call__
    req = self.application(environ, start_response)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.6/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "galaxy/web/framework/base.py", line 136, in __call__
    return self.handle_request(environ, start_response)
  File "galaxy/web/framework/base.py", line 221, in handle_request
    return body_renderer(trans, body, environ, start_response)
  File "galaxy/web/framework/base.py", line 239, in _render_body
    start_response(trans.response.wsgi_status(),
  File "galaxy/web/framework/base.py", line 473, in wsgi_status
    return "%d %s" % (exception.code, exception.title)
```