Gracefully handle hid comparison if hid is None
Fixes https://sentry.galaxyproject.org/sentry/main/issues/501183/:
```
TypeError: '<' not supported between instances of 'int' and 'NoneType'
  File "galaxy/tools/__init__.py", line 2095, in populate_model
    tool_dict = input.to_dict(request_context, other_values=other_values)
  File "galaxy/tools/parameters/basic.py", line 2000, in to_dict
    d['options']['hda'] = sorted(d['options']['hda'], key=lambda k: k['hid'], reverse=True)
TypeError: '<' not supported between instances of 'int' and 'NoneType'
  File "galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "galaxy/webapps/galaxy/api/tools.py", line 124, in build
    return tool.to_json(trans, kwd.get('inputs', kwd))
  File "galaxy/tools/__init__.py", line 2032, in to_json
    self.populate_model(request_context, self.inputs, state_inputs, tool_model['inputs'])
  File "galaxy/tools/__init__.py", line 2104, in populate_model
    tool_dict = input.to_dict(request_context)
  File "galaxy/tools/parameters/basic.py", line 2000, in to_dict
    d['options']['hda'] = sorted(d['options']['hda'], key=lambda k: k['hid'], reverse=True)
```

HDAs really should have a `hid`, but custom len files built by the custom
API endpoint don't actually get added to any history. On our old prod server
we also have a couple of datasets that are in error state and have no
hid. I'm not sure how they could ever get into `hda_list`, but this is
clearly better than failing.