Undo 1470a56d5a; remove SA bidirectional attr error
ValueError: Bidirectional attribute conflict detected: Passing object
<JobToInputDatasetAssociation at 0x7f7370943d30> to attribute
"Job.output_datasets" triggers a modify event on attribute
"Job.input_datasets" via the backref "JobToInputDatasetAssociation.job".