Fix mypy error due to alembic 1.11.0
Alembic 1.11.0 made the `table_name` argument of `op.drop_index()`
keyword-only, causing the following failure in the
test_galaxy_packages build (where alembic is not pinned):

```
galaxy/model/migrations/util.py:30: error: Too many positional arguments for
"drop_index"  [misc]
            op.drop_index(index_name, table_name)
            ^
```

xref: https://github.com/sqlalchemy/alembic/issues/1243

Also drop the unused `columns` parameter from our wrapper method,
as done already in the dev branch.