Fix installation of data manager revision updates
Without this updates of data managers fails with
```
AttributeError: 'NoneType' object has no attribute 'get'
  File "galaxy/web/framework/middleware/sentry.py", line 40, in __call__
    iterable = self.application(environ, start_response)
  File "/bioinfo/guests/mvandenb/galaxy/.venv/local/lib/python2.7/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/bioinfo/guests/mvandenb/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "galaxy/web/framework/base.py", line 136, in __call__
    return self.handle_request(environ, start_response)
  File "galaxy/web/framework/base.py", line 215, in handle_request
    body = method(trans, **kwargs)
  File "galaxy/web/framework/decorators.py", line 98, in decorator
    return func(self, trans, *args, **kwargs)
  File "galaxy/webapps/galaxy/controllers/admin_toolshed.py", line 1849, in update_to_changeset_revision
    persist=True)
  File "tool_shed/galaxy_install/metadata/installed_repository_metadata_manager.py", line 30, in __init__
    metadata_dict=metadata_dict, user=None)
  File "tool_shed/metadata/metadata_generator.py", line 63, in __init__
    self.metadata_dict = {'shed_config_filename': self.shed_config_dict.get('config_filename', None)}
```