Fix vue typescript around history annotation.
src/components/History/Layout/DetailsLayout.vue:99:9 - error TS2322: Type 'string | undefined' is not assignable to type 'string | null'.
  Type 'undefined' is not assignable to type 'string | null'.

99         annotation: props.annotation,
           ~~~~~~~~~~

  src/components/History/Layout/DetailsLayout.vue:47:40
    47 const localProps = ref<{ name: string; annotation: string | null; tags: string[] }>({
                                              ~~~~~~~~~~
    The expected type comes from property 'annotation' which is declared here on type '{ name: string; annotation: string | null; tags: string[]; }'