Add missing Werkzeug test requirement
Used in `test/unit/util/test_get_url.py` since commit
69ebbb761aa610c1eab2f92a385c34b47259ac32 .

Pin Werkzeug in `lib/galaxy/dependencies/dev-requirements.txt`
to latest version compatible with pytest-httpserver 1.0.6 .

Fix unit test collection error on Python 3.11:
```
  File "/home/runner/work/galaxy/galaxy/galaxy root/.tox/unit-coverage/lib/python3.11/site-packages/pytest_httpserver/httpserver.py", line 26, in <module>
    from werkzeug.http import parse_authorization_header
ImportError: cannot import name 'parse_authorization_header' from 'werkzeug.http' (/home/runner/work/galaxy/galaxy/galaxy root/.tox/unit-coverage/lib/python3.11/site-packages/werkzeug/http.py)
```