Encode chunk before comparing with gzip_magic
Since commit 8d8299a19315aef2f2daef278a5e8d8c47da63bb ,
`text_type(util.gzip_magic)` generates the following exception:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
```