Add ``hgweb_repo_prefix`` attribute to ``TestToolShedConfig``
Fix the following error in unit tests:

```
AttributeError: 'TestToolShedConfig' object has no attribute 'hgweb_repo_prefix'
```

caused by merging commit b00beec3d26b7dff76b32d56078bf7c90eff915b
forward.