Fix uploading workflow archives
This fixes https://sentry.galaxyproject.org/sentry/main/issues/502038/:
```
TypeError: a bytes-like object is required, not 'str'
  File "galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "galaxy/webapps/galaxy/api/workflows.py", line 361, in create
    return self.__api_import_from_archive(trans, archive_data, "uploaded file")
  File "galaxy/webapps/galaxy/api/workflows.py", line 640, in __api_import_from_archive
    if "GalaxyWorkflow" in archive_data:
```
The actual uploaded data is still invalid, but a more meaningful message
will be raised with this fix.