Fix composite data download from collection
We wrongly pass hdca (and element_identifier) into
_archive_composite_dataset, which breaks downloading composite datasets
from a collection. Fixes
https://sentry.galaxyproject.org/sentry/main/issues/290622/:
```
Exception: Unknown parameter type (<class 'galaxy.model.HistoryDatasetCollectionAssociation'>)
  File "galaxy/web/framework/middleware/sentry.py", line 43, in __call__
    iterable = self.application(environ, start_response)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "galaxy/web/framework/middleware/statsd.py", line 33, in __call__
    req = self.application(environ, start_response)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "galaxy/web/framework/base.py", line 141, in __call__
    return self.handle_request(environ, start_response)
  File "galaxy/web/framework/base.py", line 220, in handle_request
    body = method(trans, **kwargs)
  File "galaxy/webapps/galaxy/controllers/dataset.py", line 186, in display
    return data.datatype.display_data(trans, data, preview, filename, to_ext, offset=offset, ck_size=ck_size, **kwd)
  File "galaxy/datatypes/data.py", line 444, in display_data
    return self._archive_composite_dataset(trans, data, **kwd)
  File "galaxy/datatypes/data.py", line 266, in _archive_composite_dataset
    params = util.Params(kwd)
  File "galaxy/util/__init__.py", line 822, in __init__
    self.__dict__[key] = sanitize_param(value)
  File "galaxy/util/__init__.py", line 596, in sanitize_param
    raise Exception('Unknown parameter type (%s)' % (type(value)))
```